import { pgTable, uuid, varchar, text, boolean, timestamp, pgEnum, index } from 'drizzle-orm/pg-core';
import { users } from './users';
import { adsCampaigns } from './ads_campaigns';
import { adsCreatives } from './ads_creatives';

/**
 * ads_promoters
 *
 * Promoter profiles — users who distribute ads and earn revenue.
 * A user can have at most one promoter profile.
 * The type determines which sub-resources they can create:
 *   WEBSITE     → ads_promoter_websites
 *   INDIVIDUAL  → share links via ads_placements
 *   MOBILE_APP  → ads_promoter_apps
 */
export const promoterTypeEnum = pgEnum('ads_promoter_type', [
  'WEBSITE',
  'INDIVIDUAL',
  'MOBILE_APP',
]);

export const adsPromoters = pgTable(
  'ads_promoters',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id').notNull().unique().references(() => users.id, { onDelete: 'cascade' }),
    type: promoterTypeEnum('type').notNull(),
    displayName: varchar('display_name', { length: 100 }),
    bio: text('bio'),
    isActive: boolean('is_active').notNull().default(true),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('ads_promoters_user_id_idx').on(t.userId),
    index('ads_promoters_type_idx').on(t.type),
  ],
);

/**
 * ads_promoter_websites
 *
 * Website registered by a WEBSITE-type promoter.
 * Verification: owner must prove control of the domain using one of:
 *   - DNS TXT record (strong — standalone)
 *   - HTML file + Meta tag (moderate + moderate = combined strong)
 *
 * verification_token: A UUID generated by our system, inserted into
 * the chosen verification mechanism by the site owner.
 *
 * embed_ping_last_at: Updated each time the embed.js fires an embed_ping
 * event from this site — used to detect inactive/removed embeds.
 */
export const verificationStatusEnum = pgEnum('ads_verification_status', [
  'pending',
  'verified',
  'failed',
  'revoked',
]);

export const verificationMethodEnum = pgEnum('ads_verification_method', [
  'dns_txt',
  'html_file_and_meta_tag',
]);

export const adsPromoterWebsites = pgTable(
  'ads_promoter_websites',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    promoterId: uuid('promoter_id').notNull().references(() => adsPromoters.id, { onDelete: 'cascade' }),
    url: text('url').notNull(),
    domain: varchar('domain', { length: 255 }).notNull(),
    verificationToken: varchar('verification_token', { length: 100 }).notNull(),
    verificationMethod: verificationMethodEnum('verification_method').notNull(),
    verificationStatus: verificationStatusEnum('verification_status').notNull().default('pending'),
    verifiedAt: timestamp('verified_at', { withTimezone: true }),
    lastVerificationAttemptAt: timestamp('last_verification_attempt_at', { withTimezone: true }),
    verificationErrorMessage: text('verification_error_message'),
    embedPingLastAt: timestamp('embed_ping_last_at', { withTimezone: true }),
    isActive: boolean('is_active').notNull().default(true),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('ads_promoter_websites_promoter_id_idx').on(t.promoterId),
    index('ads_promoter_websites_domain_idx').on(t.domain),
    index('ads_promoter_websites_status_idx').on(t.verificationStatus),
  ],
);

/**
 * ads_promoter_apps
 *
 * Mobile app registered by a MOBILE_APP-type promoter.
 */
export const appPlatformEnum = pgEnum('ads_app_platform', ['ios', 'android', 'both']);

export const adsPromoterApps = pgTable(
  'ads_promoter_apps',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    promoterId: uuid('promoter_id').notNull().references(() => adsPromoters.id, { onDelete: 'cascade' }),
    appName: varchar('app_name', { length: 100 }).notNull(),
    bundleId: varchar('bundle_id', { length: 255 }).notNull(),
    platform: appPlatformEnum('platform').notNull(),
    storeUrl: text('store_url'),
    verificationStatus: verificationStatusEnum('verification_status').notNull().default('pending'),
    verifiedAt: timestamp('verified_at', { withTimezone: true }),
    isActive: boolean('is_active').notNull().default(true),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('ads_promoter_apps_promoter_id_idx').on(t.promoterId),
  ],
);

/**
 * ads_placements
 *
 * A placement links a campaign creative to a specific promoter resource.
 * For INDIVIDUAL promoters, placement_token is the unique identifier
 * embedded in the share link URL for tracking + Reels display.
 *
 * Share link structure:
 *   https://go.crimfig.com/ad/{placement_token}?pid={promoter_id}&cid={campaign_id}&crid={creative_id}&...
 */
export const placementStatusEnum = pgEnum('ads_placement_status', [
  'active',
  'paused',
  'completed',
  'rejected',
]);

export const adsPlacements = pgTable(
  'ads_placements',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    campaignId: uuid('campaign_id').notNull().references(() => adsCampaigns.id, { onDelete: 'cascade' }),
    creativeId: uuid('creative_id').notNull().references(() => adsCreatives.id, { onDelete: 'cascade' }),
    promoterId: uuid('promoter_id').notNull().references(() => adsPromoters.id, { onDelete: 'cascade' }),

    // Nullable — set for WEBSITE placements
    websiteId: uuid('website_id').references(() => adsPromoterWebsites.id, { onDelete: 'set null' }),

    // Nullable — set for MOBILE_APP placements
    appId: uuid('app_id').references(() => adsPromoterApps.id, { onDelete: 'set null' }),

    status: placementStatusEnum('status').notNull().default('active'),

    // Unique token used in embed code and share links for tracking
    placementToken: varchar('placement_token', { length: 64 }).notNull().unique(),

    // HMAC signature for share link validation (prevents token forgery)
    linkSignature: varchar('link_signature', { length: 128 }),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('ads_placements_campaign_id_idx').on(t.campaignId),
    index('ads_placements_promoter_id_idx').on(t.promoterId),
    index('ads_placements_token_idx').on(t.placementToken),
    index('ads_placements_status_idx').on(t.status),
  ],
);

export type AdsPromoter = typeof adsPromoters.$inferSelect;
export type NewAdsPromoter = typeof adsPromoters.$inferInsert;
export type AdsPromoterWebsite = typeof adsPromoterWebsites.$inferSelect;
export type NewAdsPromoterWebsite = typeof adsPromoterWebsites.$inferInsert;
export type AdsPromoterApp = typeof adsPromoterApps.$inferSelect;
export type NewAdsPromoterApp = typeof adsPromoterApps.$inferInsert;
export type AdsPlacement = typeof adsPlacements.$inferSelect;
export type NewAdsPlacement = typeof adsPlacements.$inferInsert;
